
  // DO NOT MODIFY. This file is automatically generated by the test suite.

  
  import { mongooseAdapter } from '@payloadcms/db-mongodb'

  export const databaseAdapter = mongooseAdapter({
    ensureIndexes: true,
    // required for connect to detect that we are using a memory server
    mongoMemoryServer:  global._mongoMemoryServer,
    url:
      process.env.MONGODB_MEMORY_SERVER_URI ||
      process.env.DATABASE_URI ||
      'mongodb://127.0.0.1/payloadtests',
    collation: {
      strength: 1,
    },
  })
  